apiVersion: v1
kind: Pod
metadata:
  name: volume-secret-app
spec:
  containers:
  - name: volume-secret-app
    image: sailusha/app-secret:3.0
    ports:
      - containerPort: 8080
  volumes:
  - name: app-secret-volume
    secret:
      secretName: app-vol-secret 
