apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-np
spec:
  type: NodePort
  selector:
     app: nginx
  ports:
    - protocol: TCP
      port: 5580
      targetPort: 80
      nodePort: 31280
