apiVersion: v1
kind: Pod
metadata:
  name: simple-cm-app1
spec:
  containers:
  - name: simple-cm-app1
    image: sailusha/cm-app1:1.0
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        valueFrom:
          configMapKeyRef:
            name: app-config1
            key: APP_COLOR1
