apiVersion: v1
kind: Pod
metadata:
  name: simple-cm-app
spec:
  containers:
  - name: simple-cm-app
    image: sailusha/cm-app:1.0
    ports:
      - containerPort: 8080
    envFrom:
      - configMapRef:
          name: app-config
